### ISSUE TITLE
Python error in main script

### ISSUE THREAD

**Issue by EgoPros** [matthewmiglio/py-clash-bot#102]
Python [ 3.11.0 ]
![image](https://user-images.githubusercontent.com/82798175/206877587-564d68ef-8b69-4285-af40-e900f91ac5ca.png)

**Comment by marmig0404** [comment]
program requires admin perms to run, looks like you got it figure out though.

**Comment by PlainAwesome10** [comment]
how was this resolved, I've opened as admin...same still
