### ISSUE TITLE
Crash after clicking on the arena trophies

### ISSUE THREAD

**Issue by Fortnitian** [matthewmiglio/py-clash-bot#103]
**Describe the bug**
You start the bot it tries to randomzie the deck, but it doesn't work and noone even wants this, please just battle with the current one...
but anyways after it is done with doing npthing because that doesn't even work it clicks on the tropy road and then it just restarts the entire bot.
**To Reproduce**
Start the bot

**Expected behavior**
The bot just goes into a battle?

**Screenshots**
It restarts with creating vm?

**Desktop (please complete the following information):**
Windows 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matthewmiglio** [comment]
Randomize deck (as well as every other function) is toggleable in the jobs list in the topleft of the GUI. Select only the tasks you'd like the bot to do.

In reference to the actual error, id require screenshots of either the VM or the GUI, or a more thorough description.

**Comment by matthewmiglio** [comment]
randomize_and_select_deck_2() in deck.py has been refactored, so any previous error is now deprecated.
