### ISSUE TITLE
Clashbot will not function when i log in with my supercell ID

### ISSUE THREAD

**Issue by HamJingPeng** [matthewmiglio/py-clash-bot#125]
**Describe the bug**
Clashbot goes into a loop, clicking the corner of the clash royale app while trying to identify if its in the main menu of clash royale. (only starts happening after i connect to my supercell ID)

**To Reproduce**
1. Open up clashbot as per the usual instruction
2. It will trigger an instance for memu and open up clash royale.
3. Clashbot will get stuck in a loop trying to identify when clash royale's main menu has loaded.
4. It will consistently click on the corner of the app where there are no buttons.
5. After multiple tries, clashbot will attempt to reboot another instance of Memu and the same actions from 2. - 4. repeats endlessly.

**Expected behavior**
Clashbot would have identified that it is already in the main menu of clash royale and start operating as per the jobs ticked. (It works if i do not log in my supercell ID, meaning just the base game as a new account)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version py-clash-bot-v1.1.0-win64.msi
 
**Additional context**
Sorry, i am extremely new to this community, and I am trying to give as much details as I can. Please pardon me if I'm missing out any key details you might need to identify any errors.

**Comment by marmig0404** [comment]
Thanks for opening a bug report, the information you provided is great. Could you also share your screen resolution?

There's a possibility that the Clash Royale UI could have changed since this version which causes the main menu to not be detected when a new supercell ID has been added. Could you capture a screenshot which shows the state of the bot's UI and the main menu screen of Clash Royale? The status of the bot will show that it is looking for the main menu and then after not detecting it for some time, it would say it is restarting due to too many attempts to detect the screen.

**Comment by HamJingPeng** [comment]
> Thanks for opening a bug report, the information you provided is great. Could you also share your screen resolution?

My screen is 1980x 1080.
The memu app resolution is 
![aimage](https://user-images.githubusercontent.com/122822095/212805583-32f106e2-fb92-492f-bb2b-cec2ac941805.png)


> There's a possibility that the Clash Royale UI could have changed since this version which causes the main menu to not be detected when a new supercell ID has been added. Could you capture a screenshot which shows the state of the bot's UI and the main menu screen of Clash Royale? The status of the bot will show that it is looking for the main menu and then after not detecting it for some time, it would say it is restarting due to too many attempts to detect the screen.

The bot shows this when trying to identify that it's in the main menu and goes on a loop (restarting and turning on another instance of memu)
![image](https://user-images.githubusercontent.com/122822095/212805767-e750dedf-0cfa-49f4-8bb6-ee468edd5fbe.png)

**Comment by HamJingPeng** [comment]
I think I figured out the issue, clash bot only recognizes trophy road as the main menu. In this case, I'm in path of legends, which is causing it not to work. I switched back to trophy road, and the bot works now! :)

**Comment by matthewmiglio** [comment]
Thanks for sharing that problem, and investigating a fix. I'll the underlying issue and create a new release soon.

I appreciate your thorough descriptions!
