### ISSUE TITLE
AHK installation failed aborting!

### ISSUE THREAD

**Issue by PlainAwesome10** [matthewmiglio/py-clash-bot#139]
idk what this means I'm completely new and it might be a simple fix but I can't seem to get it

**Comment by marmig0404** [comment]
This is an on going issue with some of the 2.x pre-releases, can you try using the [latest stable version](https://github.com/matthewmiglio/py-clash-bot/releases/latest)?

**Comment by PlainAwesome10** [comment]
> This is an on going issue with some of the 2.x pre-releases, can you try using the [latest stable version](https://github.com/matthewmiglio/py-clash-bot/releases/latest)?

I did the latest version had some issues with main process errors, realized I need to use MEnu and that emulator won’t even open clash for me so I’m at a dead end

**Comment by marmig0404** [comment]
can you open MEmu and get to clash royale manually? if not you may need to reference [MEmu troubleshooting documentation](https://www.memuplay.com/blog/how-to-solve-start-failure.html)

**Comment by PlainAwesome10** [comment]
> can you open MEmu and get to clash royale manually? if not you may need to reference [MEmu troubleshooting documentation](https://www.memuplay.com/blog/how-to-solve-start-failure.html)

What do you mean manually, and I have tried the troubleshooting process.

**Comment by marmig0404** [comment]
Without using pyclashbot, can you get MEmu started and running? Sometimes it has trouble on different setups depending on virtualization settings.

If MEmu isn't the problem, i'll need more information on which part of the process that the bot is stuck on when trying to open clash royale.

**Comment by marmig0404** [comment]
Closing this problem as the original problem has been fixed in the 2.0 branch. Will be merged in for eventual 2.0 release.
