### ISSUE TITLE
No such file or directory: 'C:\\...\\Desktop\\ssid_account_index_log.txt'

### ISSUE THREAD

**Issue by matthewmiglio** [matthewmiglio/py-clash-bot#164]
**Describe the bug**
ssid account index log file not found

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Display resolution: 4k
 - Version 2.0.0-12

**Comment by matthewmiglio** [comment]
deprecated issue

**Comment by zalmosside** [comment]
hello, i have this problem too. can you help me? thanks!

**Comment by marmig0404** [comment]
@zalmosside Can you confirm you are running the latest version? I was fixed a while back.

**Comment by marmig0404** [comment]
@zalmosside Working on a new build for this issue, look for 1.1.3 soon. Was fixed in a patch 2 weeks ago, but never fully released.
