### ISSUE TITLE
Account switching is not working

### ISSUE THREAD

**Issue by gustavokei** [matthewmiglio/py-clash-bot#199]
**Describe the bug**
Account switching is not working

**To Reproduce**
1. Start the bot with more than one supercell id logged in
2. When the bot opens up the accounts screen (while doing `f"Switching accounts to account number {str(account_number)}"`), it crashes with:
`Error: [Errno 2] No such file or directory: 'C:\\Users\\matmi\\OneDrive\\Desktop\\ssid_account_index_log.txt'`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Display resolution: 1366x768 and tried with 1400x900 same results
 - 1.1.2

**Comment by marmig0404** [comment]
Working on a new build for this issue, look for 1.1.3 soon.
Was fixed in a patch 2 weeks ago, but never fully released.
