### ISSUE TITLE
Feature Request: Use ADB for emulator/client interaction

### ISSUE THREAD

**Issue by martinmiglio** [matthewmiglio/py-clash-bot#210]
Using Android Debug Bridge for emulator and client interaction would allow for the mouse and keyboard to be used while bot is running.
ADB can be accessed using [pymemuc](https://github.com/marmig0404/pymemuc) or [adb-shell](https://github.com/JeffLIrion/adb_shell) or [pure-python-adb](https://pypi.org/project/pure-python-adb/), all valid options to investigate.

**Comment by marmig0404** [comment]
Using pymemuc has potential as other options would require finding the emulator's ADB port, whereas pymemuc has knowledge of device info give emulator index/name.

Example implementation:
```python
import pymemuc

pmc = pymemuc.PyMemuc(debug=True)

# send adb command to press home button
pmc.send_adb_command_vm('shell input keyevent 3', vm_index=1)
```
