### ISSUE TITLE
MEmu failing to reopen after restart

### ISSUE THREAD

**Issue by EthanNielsen** [matthewmiglio/py-clash-bot#252]
**Describe the bug**
When a falure occurs the bot closes MEmu to restart it, but it gets stuck "closing all things MEmu related"

**To Reproduce**
1. Start up Bot
2. Run bot for about an hour
3. Mouse gets stuck or another issue happens that requires a reset
4. Py-clashbot stays stuck on "closing all things MEmu related"

**Expected behavior**
I expect the bot to reopen the virtual MEmu client so that it can continue playing the game, but it just gets stuck.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Display resolution: 1366 x 768
 - Version: 10.0.22000 Build 22000

**Additional context**
After the recent update the bot crashes whenever it's about to enable a 2v2 match, could that be because of new graphics?

**Comment by martinmiglio** [comment]
this issue should be fixed in v1.2.2 pre-releases
