### ISSUE TITLE
0:00:00 - 0W|0L : MEmu or Multiple Instance Manager not detected!

### ISSUE THREAD

**Issue by ow3rk1ll** [matthewmiglio/py-clash-bot#27]
Hello Dear developer i am having memu is not detected issue but i freshly installed memu should i installed a specific version of memu maybe ?

**Comment by matthewmiglio** [comment]
Good morning. Before launching the bot, make sure both the MEmu Multi Instance Manager and the MEmu client are both open.

Also, check the settings for your MEmu client launch are the same as shown in the README.md.

If none of these fixes work, please let me know which version of MEmu you are using!

**Comment by matthewmiglio** [comment]
accidental issue close
