### ISSUE TITLE
Image recognition broken

### ISSUE THREAD

**Issue by matthewmiglio** [matthewmiglio/py-clash-bot#283]
Image recognition broken in implementation in request state.

Image recognition methods are successfully implemented in src/pyclashbot/bot/card_detection.py but fail elsewhere.

broken code:
```python
def find_request_button(vm_index):
    folder_str = "request_button"

    img = screenshot(vm_index)

    size = get_file_count(folder_str)

    names = make_reference_image_list(size)

    locations: list[list[int] | None] = find_references(
        image=img, folder=folder_str, names=names, tolerance=0.97
    )

    print(locations)
```
Associated images: 
![1](https://github.com/matthewmiglio/py-clash-bot/assets/105177840/6426b14e-22ef-4f24-82e9-675d4832bd10)

**Comment by martinmiglio** [comment]
OpenCV didn't like the  `PNG file > PIL.Image  > numpy.ndarray` conversion, replaced all use of `PIL.open` with `cv2.imread` to handle the `PNG file > ndarray`. Probably related to the screenshotting from the emulator being in a different pixel format.
