### ISSUE TITLE
Incorrect fireball/rocket placement in 2V2

### ISSUE THREAD

**Issue by Feifan1010** [matthewmiglio/py-clash-bot#296]
**Describe the bug**

**To Reproduce**
1. Go in a 2v2 match
2. run bot and wait until it places a fireball or rocket

**Expected behavior**
It should miss the tower

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Display resolution: [1920x1080
 - Version V2.0.0

**Additional context**

**Comment by martinmiglio** [comment]
Fixed in v2.0.1
