### ISSUE TITLE
"Waiting for clash main menu"

### ISSUE THREAD

**Issue by ludwig7685** [matthewmiglio/py-clash-bot#305]
After it started clash royale, nothing happens. in the logs it says:"
[start] Successfully initialized Clash app
INFO:2023-09-13 22:20:53,243 Successfully initialized Clash app
INFO:2023-09-13 22:20:57,244 [start] Manually waiting for clash main page. 4.0/10
INFO:2023-09-13 22:21:01,245 [start] Manually waiting for clash main page. 8.0/10
INFO:2023-09-13 22:21:05,246 [start] Manually waiting for clash main page. 12./10
INFO:2023-09-13 22:21:05,246 [start] Waiting for clash main menu
INFO:2023-09-13 22:21:40,550 [start] Stopping"

( i manually stopped the bot. )

just nothing happens in the main menu. and when i manually press play, it says over and over i dont have a card selected, if i select a card in the bar, it gets placed like 0.5 secounds after selecting, on the left side of the left tower.

**Comment by ahmify** [comment]
Same exact issue here ):

**Comment by nardbyte** [comment]
I have the same problem don't start to execute bot.

**Comment by martinmiglio** [comment]
This issue should be fixed in v2.0.1
