### ISSUE TITLE
make fight loop

### ISSUE THREAD

**Issue by knottty** [matthewmiglio/py-clash-bot#34]
just make loop for fights. it takes alot of time to check clan / upgrade cards etc.

**Comment by knottty** [comment]
u should make config.py until graphical interface is not added

**Comment by marmig0404** [comment]
Just added, making a new release with config.json included, let me know what you think.

**Comment by marmig0404** [comment]
[Release 0.4.20](https://github.com/matthewmiglio/py-clash-bot/releases/tag/v0.4.20) includes a [config.json](https://github.com/matthewmiglio/py-clash-bot/blob/master/pyclashbot/config.json) for user config. See [readme.md](https://github.com/matthewmiglio/py-clash-bot/blob/master/README.md) for more info on how to change settings.
