### ISSUE TITLE
Canty make Bot to work Help Needed !!

### ISSUE THREAD

**Issue by saabtech** [matthewmiglio/py-clash-bot#83]
When I tried both Windows and with PIP. the bot install and I followed the instruction to configure MEMU emulator, but I get the below message, Screenshot|:

![image](https://user-images.githubusercontent.com/85780689/195824365-65f602b6-d01a-432a-8b8b-21d822afd234.png)

I tick the fight, 1 account , and Giant card, when I hit start, I get error as shown in the screenshot above. Let me know if am missing any steps.

**Comment by matthewmiglio** [comment]
Ill take a look into this issue today. Thanks for letting me know.

**Comment by matthewmiglio** [comment]
A new version is out that should work for you. If you encounter another issue please make another issue on GitHub.
