### ISSUE TITLE
ERROR: 'AHK' object has no attribute 'minimize_window'

### ISSUE THREAD

**Issue by yungwack** [matthewmiglio/py-clash-bot#92]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matthewmiglio** [comment]
Thanks for sharing. I'll release a version that fixes this issue in a few hours.

**Comment by matthewmiglio** [comment]
Version 1.0.8 is out and fixed this issue. If you encounter another problem please open another issue.

Thanks again.
